---
deployment:
  tasks:
    - (echo "--composer--"; which composer; echo "--curl--"; which curl; echo "--allow_url_fopen--"; php -r 'var_dump(ini_get("allow_url_fopen"));'; echo "--php version--"; php -v; echo "--done--") 2>&1
