---
deployment:
  tasks:
    - /opt/cpanel/ea-php83/root/usr/bin/php /home/polnutsp/app_live2/artisan tinker --execute="echo 'setting.email=' . (\App\Models\Setting::current()->email ?? 'NULL');"
    - which sendmail
    - tail -n 60 /home/polnutsp/app_live2/storage/logs/laravel.log
